import * as THREE from 'three';
import { createRenderer, fitViewport } from './core/renderer.js';
import { makeMaterial, palette } from './assets/materials.js';
import { createPlayer } from './player.js';
import './styles.css';
import './fps-controls.css';
const canvas=document.querySelector('#scene-canvas'),renderer=createRenderer(canvas),scene=new THREE.Scene();scene.background=new THREE.Color(0x142b34);scene.fog=new THREE.Fog(0x142b34,10,24);
const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,40);camera.position.set(0,1.72,6.6);camera.lookAt(0,1.65,-1.8);
const M={wall:makeMaterial(0x315d60),wall2:makeMaterial(0x23484f),floor:makeMaterial(0x6b5146),wood:makeMaterial(0x754e3d),trim:makeMaterial(0xe5c28b),leather:makeMaterial(0xc96755),metal:makeMaterial(0xb7c3b4,.45),glass:makeMaterial(0x83b5aa,.3),cream:makeMaterial(0xf3efe7),gold:makeMaterial(0xf3b65b),teal:makeMaterial(0x2e7774)};
const shop=new THREE.Group();scene.add(shop);function mesh(g,m,p=[0,0,0],name=''){const x=new THREE.Mesh(g,m);x.position.set(...p);x.name=name;x.castShadow=x.receiveShadow=true;shop.add(x);return x}function box(s,m,p,n){return mesh(new THREE.BoxGeometry(...s),m,p,n)}
// small room shell
box([9,.15,8],M.floor,[0,0,-1.2],'floor');box([9,4.2,.15],M.wall,[0,2.1,-5.15],'back wall');box([.15,4.2,8],M.wall2,[-4.5,2.1,-1.2],'left wall');box([.15,4.2,8],M.wall2,[4.5,2.1,-1.2],'right wall');box([9,.12,8],M.wall2,[0,4.2,-1.2],'ceiling');
// station and framed mirror
box([3.9,.18,.8],M.wood,[0,1.02,-4.35],'counter');box([4.1,.12,.88],M.trim,[0,1.15,-4.35],'countertop');box([.18,1.45,.65],M.wood,[-1.65,.38,-4.35],'storage');box([.18,1.45,.65],M.wood,[1.65,.38,-4.35],'storage');
box([3.65,2.35,.14],M.trim,[0,2.65,-4.45],'mirror frame');box([3.3,2,.04],M.glass,[0,2.65,-4.54],'mirror');
for(const x of [-1.48,-.74,0,.74,1.48]){const l=mesh(new THREE.CylinderGeometry(.09,.09,.38,10),M.gold,[x,2.65,-4.66],'mirror bulb');l.rotation.x=Math.PI/2}
// chair: back, seat, arms, headrest, pedestal, footrest
const chair=new THREE.Group();chair.position.set(0,0,-2.35);shop.add(chair);function cm(g,m,p,n){const x=new THREE.Mesh(g,m);x.position.set(...p);x.castShadow=x.receiveShadow=true;x.name=n;chair.add(x);return x}cm(new THREE.BoxGeometry(1.35,1.55,.48),M.leather,[0,1.55,0],'chair back');cm(new THREE.BoxGeometry(1.5,.3,1.15),M.leather,[0,.82,0],'chair seat');cm(new THREE.BoxGeometry(.16,.5,1.05),M.wood,[-.78,1.06,0],'armrest');cm(new THREE.BoxGeometry(.16,.5,1.05),M.wood,[.78,1.06,0],'armrest');cm(new THREE.BoxGeometry(.9,.35,.38),M.leather,[0,2.5,0],'headrest');cm(new THREE.CylinderGeometry(.13,.18,1.2,10),M.metal,[0,.28,0],'chair base');cm(new THREE.CylinderGeometry(.65,.78,.14,16),M.metal,[0,.08,0],'chair base');cm(new THREE.BoxGeometry(1.15,.12,.42),M.metal,[0,.36,.62],'footrest');
// side shelves, bottles and grooming props
box([2.2,.12,.42],M.wood,[-3.25,2.8,-4.55],'shelf');box([2.2,.12,.42],M.wood,[-3.25,3.55,-4.55],'shelf');for(const p of [[-3.8,3.05],[ -3.25,3.05],[-2.7,3.05],[-3.55,3.8],[-2.9,3.8]]){mesh(new THREE.CylinderGeometry(.12,.15,.38,8),p[0]===-3.25?M.gold:M.coral,[p[0],p[1],-4.5],'product bottle')}
function prop(g,m,p,n,parent=shop){return mesh(g,m,p,n,parent)}
const toolY=1.27, backZ=-4.35;
function group(name,p){const g=new THREE.Group();g.name=name;g.position.set(...p);shop.add(g);return g}function part(g,geo,matl,p,n){const x=new THREE.Mesh(geo,matl);x.position.set(...p);x.name=n;x.castShadow=x.receiveShadow=true;g.add(x);return x}
let g=group('ElectricClipper',[-1.35,toolY,backZ]);part(g,new THREE.BoxGeometry(.42,.22,.3),M.metal,[0,0,0],'clipper body');part(g,new THREE.CylinderGeometry(.13,.16,.42,8),M.teal,[0,-.01,.08],'clipper grip').rotation.z=Math.PI/2;part(g,new THREE.BoxGeometry(.34,.07,.1),M.gold,[0,.14,-.16],'clipper cutting head');for(let i=-2;i<3;i++)part(g,new THREE.BoxGeometry(.035,.05,.1),M.cream,[i*.06,.18,-.2],'clipper blade tooth');part(g,new THREE.CylinderGeometry(.035,.035,.02,8),M.coral,[.12,.12,.1],'power button').rotation.x=Math.PI/2;
g=group('HairTrimmer',[-.82,toolY,backZ]);part(g,new THREE.BoxGeometry(.22,.16,.22),M.teal,[0,0,0],'trimmer body');part(g,new THREE.BoxGeometry(.12,.28,.16),M.teal,[0,-.18,.02],'trimmer grip');part(g,new THREE.BoxGeometry(.2,.05,.1),M.gold,[0,.1,-.14],'trimmer head');
function scissors(name,x,toothed){g=group(name,[x,toolY,backZ]);const a=part(g,new THREE.BoxGeometry(.42,.035,.06),M.metal,[.18,0,0],'blade');a.rotation.y=.16;const b=part(g,new THREE.BoxGeometry(.42,.035,.06),M.metal,[-.18,0,0],'blade');b.rotation.y=-.16;if(toothed)for(let i=-2;i<3;i++)part(g,new THREE.ConeGeometry(.025,.08,4),M.gold,[i*.07,.06,0],'tooth');part(g,new THREE.SphereGeometry(.035,6,4),M.gold,[0,0,0],'pivot');part(g,new THREE.TorusGeometry(.1,.025,6,12),M.gold,[-.28,-.06,0],'finger loop').rotation.x=Math.PI/2;part(g,new THREE.TorusGeometry(.1,.025,6,12),M.gold,[.28,-.06,0],'finger loop').rotation.x=Math.PI/2}scissors('BarberScissors',-.1,false);scissors('ThinningScissors',.55,true);
g=group('BarberComb',[1.2,toolY,backZ]);part(g,new THREE.BoxGeometry(.5,.045,.1),M.teal,[0,.03,0],'comb spine');for(let i=-5;i<6;i++)part(g,new THREE.BoxGeometry(.025,.13,.07),M.teal,[i*.04,-.04,0],'comb tooth');
g=group('HairBrush',[-1.55,toolY,backZ+.15]);part(g,new THREE.CylinderGeometry(.06,.07,.35,8),M.wood,[0,-.05,0],'brush handle').rotation.z=Math.PI/2;part(g,new THREE.CylinderGeometry(.13,.16,.12,8),M.coral,[.2,.02,0],'brush head').rotation.z=Math.PI/2;for(let i=-2;i<3;i++)part(g,new THREE.BoxGeometry(.025,.08,.025),M.cream,[.2+i*.04,.1,0],'bristle');
g=group('SprayBottle',[-.35,toolY+.12,backZ+.08]);part(g,new THREE.CylinderGeometry(.13,.16,.35,8),M.teal,[0,0,0],'bottle body');part(g,new THREE.CylinderGeometry(.07,.07,.14,8),M.teal,[0,.24,0],'bottle neck');part(g,new THREE.BoxGeometry(.18,.05,.16),M.coral,[.1,.32,0],'trigger');part(g,new THREE.BoxGeometry(.16,.04,.05),M.gold,[.18,.36,0],'nozzle');
for(const [x,c] of [[.05,M.coral],[.42,M.gold],[.79,M.teal]]){g=group('ProductJar',[x,toolY+.08,backZ-.02]);part(g,new THREE.CylinderGeometry(.13,.14,.18,10),c,[0,0,0],'jar');part(g,new THREE.CylinderGeometry(.14,.14,.05,10),M.cream,[0,.115,0],'lid');part(g,new THREE.BoxGeometry(.16,.06,.02),M.cream,[0,0,-.14],'label')}
g=group('HairDryer',[1.55,toolY,backZ+.12]);part(g,new THREE.SphereGeometry(.2,8,6),M.metal,[0,.12,0],'dryer housing');part(g,new THREE.CylinderGeometry(.08,.1,.35,8),M.teal,[0,-.2,0],'dryer handle');part(g,new THREE.CylinderGeometry(.1,.14,.22,8),M.metal,[0,.13,-.2],'dryer nozzle').rotation.x=Math.PI/2;
g=group('BarberRazor',[-1.1,toolY+.04,backZ+.16]);part(g,new THREE.BoxGeometry(.4,.035,.06),M.metal,[0,0,0],'razor blade');part(g,new THREE.BoxGeometry(.28,.06,.08),M.wood,[.2,0,.02],'razor handle');part(g,new THREE.CylinderGeometry(.04,.04,.03,8),M.gold,[.12,0,0],'razor pivot').rotation.x=Math.PI/2;
g=group('NeckDuster',[-1.65,toolY+.12,backZ-.05]);part(g,new THREE.CylinderGeometry(.05,.06,.3,8),M.wood,[0,-.08,0],'duster handle').rotation.z=Math.PI/2;part(g,new THREE.SphereGeometry(.13,8,6),M.coral,[.18,.05,0],'duster brush');
for(const x of [-.7,-.35]){g=group('FoldedTowel',[x,toolY+.05,backZ+.18]);for(let i=0;i<3;i++)part(g,new THREE.BoxGeometry(.3,.035,.25),M.cream,[0,i*.035,0],'towel fold')}
// Organized workstation details: tray, guards, labels, bottles, and wall holder.
const tray=group('ToolTray',[-.15,1.24,-4.58]);part(tray,new THREE.BoxGeometry(1.55,.06,.38),M.metal,[0,0,0],'tray base');for(const x of [-.72,.72])part(tray,new THREE.BoxGeometry(.06,.12,.38),M.wood,[x,.07,0],'tray rim');for(const z of [-.15,.15])part(tray,new THREE.BoxGeometry(1.55,.12,.05),M.wood,[0,.07,z],'tray rim');
for(const x of [-.55,-.25,.05]){g=group('ClipperGuard',[x,1.3,-4.7]);part(g,new THREE.BoxGeometry(.18,.12,.12),M.teal,[0,0,0],'guard base');for(let i=-2;i<3;i++)part(g,new THREE.BoxGeometry(.02,.08,.05),M.cream,[i*.03,.08,-.07],'guard tooth')}
for(const [x,h,c] of [[-2.1,.5,M.gold],[-1.7,.62,M.teal],[-1.3,.48,M.coral]]){g=group('ShampooBottle',[x,1.2+h/2,-4.5]);part(g,new THREE.CapsuleGeometry(.14,h/2-.08,4,8),c,[0,0,0],'bottle body');part(g,new THREE.CylinderGeometry(.07,.08,.12,8),c,[0,h/2-.02,0],'bottle neck');part(g,new THREE.BoxGeometry(.14,.05,.1),M.cream,[0,.25,-.14],'bottle label');part(g,new THREE.CylinderGeometry(.08,.08,.05,8),M.gold,[0,h/2+.07,0],'bottle cap')}
g=group('Disinfectant',[-.9,1.28,-4.5]);part(g,new THREE.CylinderGeometry(.12,.14,.35,8),M.glass,[0,0,0],'container');part(g,new THREE.CylinderGeometry(.07,.07,.12,8),M.gold,[0,.23,0],'cap');part(g,new THREE.BoxGeometry(.14,.06,.02),M.cream,[0,0,-.13],'label');
g=group('WallToolHolder',[2.95,2.1,-4.98]);part(g,new THREE.BoxGeometry(1.25,.8,.08),M.wood,[0,0,0],'holder plate');for(let i=-1;i<2;i++){part(g,new THREE.CylinderGeometry(.035,.035,.28,8),M.gold,[i*.35,-.1,-.12],'holder hook');part(g,new THREE.TorusGeometry(.07,.018,6,10),M.metal,[i*.35,.18,-.16],'hanging tool').rotation.x=Math.PI/2}
g=group('FoldedCape',[2.7,.35,-3.5]);for(let i=0;i<3;i++)part(g,new THREE.BoxGeometry(.9,.035,.55),M.teal,[0,i*.035,0],'cape fold');part(g,new THREE.TorusGeometry(.13,.025,6,12),M.gold,[0,.13,-.25],'cape collar').rotation.x=Math.PI/2;
// door and wall decoration
box([1.25,2.65,.14],M.wood,[3.35,1.42,-5.05],'entrance door');box([.92,1.8,.04],M.glass,[3.35,1.55,-5.14],'door glass');prop(new THREE.TorusGeometry(.08,.025,6,12),M.gold,[2.92,1.5,-5.22],'door handle').rotation.x=Math.PI/2;box([1.2,.7,.08],M.trim,[-2.85,2.35,-5.15],'wall art');
// One-time world-space contact placement using actual transformed geometry bounds.
function placeOnTop(object,surface){scene.updateMatrixWorld(true);const objectBox=new THREE.Box3().setFromObject(object);const surfaceBox=new THREE.Box3().setFromObject(surface);object.position.y += surfaceBox.max.y-objectBox.min.y;scene.updateMatrixWorld(true);return object}
const named=name=>{const found=[];scene.traverse(o=>{if(o.name===name)found.push(o)});return found};
const countertop=named('countertop')[0];if(countertop){[...named('clippers'),...named('scissors'),...named('comb'),...named('towel')].forEach(o=>placeOnTop(o,countertop))}
const shelves=named('shelf');named('product bottle').forEach((b,i)=>{const shelf=shelves[i<3?0:1];if(shelf)placeOnTop(b,shelf)});
const floor=named('floor')[0],base=named('chair base')[1];if(floor&&base)placeOnTop(base,floor);const door=named('entrance door')[0];if(floor&&door)placeOnTop(door,floor);
const hemi=new THREE.HemisphereLight(0xb9d8d0,0x17242a,1.8);scene.add(hemi);const key=new THREE.DirectionalLight(0xffd7ad,2.5);key.position.set(-4,7,4);key.castShadow=true;key.shadow.mapSize.set(512,512);scene.add(key);for(const p of [[-1.1,3.7,-4.1],[0,3.7,-4.1],[1.1,3.7,-4.1]]){const l=new THREE.PointLight(0xffbd70,1.5,4);l.position.set(...p);scene.add(l)}
const player=createPlayer(camera,scene,renderer),interaction=createChairInteraction(camera,player,chair),menu=document.querySelector('.menu'),back=document.querySelector('#shop-back'),controls=document.querySelector('#controls');function enterShop(){menu.classList.add('hidden');back.classList.add('visible');controls.classList.add('visible');document.body.classList.add('in-shop');player.reset()}function exitShop(){menu.classList.remove('hidden');back.classList.remove('visible');controls.classList.remove('visible');document.body.classList.remove('in-shop');player.reset()}document.querySelector('[data-panel="play"]').addEventListener('click',enterShop);back.addEventListener('click',exitShop);
const modal=document.querySelector('#modal'),content=document.querySelector('#panel-content');const copy={settings:['Settings','Audio, graphics, and controls will be available here.'],about:['About Barber','A stylized first-person barber simulator built for small screens and big style.']};function openPanel(k){content.innerHTML=`<h2>${copy[k][0]}</h2><p>${copy[k][1]}</p>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}function closePanel(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}document.querySelectorAll('[data-panel]:not([data-panel="play"])').forEach(b=>b.addEventListener('click',()=>openPanel(b.dataset.panel)));document.querySelector('.close').addEventListener('click',closePanel);modal.addEventListener('click',e=>{if(e.target===modal)closePanel()});
const clock=new THREE.Clock();function render(){player.update(Math.min(clock.getDelta(),.05));interaction.update(performance.now());renderer.render(scene,camera);requestAnimationFrame(render)}addEventListener('resize',()=>fitViewport(camera,renderer),{passive:true});fitViewport(camera,renderer);render();
