import * as THREE from 'three';
import { createRenderer, fitViewport } from './core/renderer.js';
import { makeMaterial, palette } from './assets/materials.js';
import { createPlayer } from './player.js';
import './styles.css';
const canvas=document.querySelector('#scene-canvas'),renderer=createRenderer(canvas),scene=new THREE.Scene();scene.background=new THREE.Color(0x142b34);scene.fog=new THREE.Fog(0x142b34,10,24);
const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,40);camera.position.set(0,1.72,6.6);camera.lookAt(0,1.65,-1.8);
const M={wall:makeMaterial(0x315d60),wall2:makeMaterial(0x23484f),floor:makeMaterial(0x6b5146),wood:makeMaterial(0x754e3d),trim:makeMaterial(0xe5c28b),leather:makeMaterial(0xc96755),metal:makeMaterial(0xb7c3b4,.45),glass:makeMaterial(0x83b5aa,.3),cream:makeMaterial(0xf3efe7),gold:makeMaterial(0xf3b65b),teal:makeMaterial(0x2e7774)};
const shop=new THREE.Group();scene.add(shop);function mesh(g,m,p=[0,0,0],name='',parent=shop){const x=new THREE.Mesh(g,m);x.position.set(...p);x.name=name;x.castShadow=x.receiveShadow=true;parent.add(x);return x}function box(s,m,p,n,parent=shop){return mesh(new THREE.BoxGeometry(...s),m,p,n,parent)}
// small room shell
box([9,.15,8],M.floor,[0,0,-1.2],'floor');box([9,4.2,.15],M.wall,[0,2.1,-5.15],'back wall');box([.15,4.2,8],M.wall2,[-4.5,2.1,-1.2],'left wall');box([.15,4.2,8],M.wall2,[4.5,2.1,-1.2],'right wall');box([9,.12,8],M.wall2,[0,4.2,-1.2],'ceiling');
// Explicit barber-station build: all dimensions are local to one assembly.
const station=new THREE.Group();station.name='BarberStation';shop.add(station);
const stationMesh=(g,m,p,n)=>mesh(g,m,p,n,station);
const counterTopY=1.12, counterW=3.15, counterD=.68;
const counter=new THREE.Group();counter.name='Counter';station.add(counter);
const counterTop=stationMesh(new THREE.BoxGeometry(counterW,.12,counterD),M.trim,[0,counterTopY-.06,-4.2],'Countertop');
stationMesh(new THREE.BoxGeometry(counterW,.98,counterD-.06),M.wood,[0,counterTopY-.12-.49,-4.2],'CounterBody');
const mirror=new THREE.Group();mirror.name='Mirror';station.add(mirror);const mmesh=(g,m,p,n)=>{const x=new THREE.Mesh(g,m);x.position.set(...p);x.name=n;x.castShadow=x.receiveShadow=true;mirror.add(x);return x};mmesh(new THREE.BoxGeometry(2.2,1.55,.12),M.trim,[0,2.65,-4.55],'MirrorFrame');mmesh(new THREE.BoxGeometry(1.9,1.25,.04),M.glass,[0,2.65,-4.63],'MirrorSurface');
const shelf=stationMesh(new THREE.BoxGeometry(1.9,.12,.3),M.wood,[-2.7,2.8,-4.52],'Shelf');const shelfTop=2.86;for(const [x,y,h,c] of [[-3.25,shelfTop,.42,M.gold],[-2.7,shelfTop,.34,M.coral],[-2.15,shelfTop,.48,M.teal]])stationMesh(new THREE.CylinderGeometry(.12,.15,h,8),c,[x,y+h/2,-4.52],'Product');
const tray=stationMesh(new THREE.BoxGeometry(1.35,.06,.38),M.metal,[1.35,counterTopY+.03,-4.2],'ToolTray');const trayTop=counterTopY+.06;stationMesh(new THREE.BoxGeometry(.48,.16,.25),M.metal,[1.05,trayTop+.08,-4.2],'Clippers');const scissors=stationMesh(new THREE.TorusGeometry(.14,.025,6,12,Math.PI*1.7),M.gold,[1.42,trayTop+.025,-4.2],'Scissors');scissors.rotation.x=Math.PI/2;stationMesh(new THREE.BoxGeometry(.45,.04,.1),M.teal,[1.72,trayTop+.02,-4.2],'Comb');
const chair=new THREE.Group();chair.name='BarberChair';chair.position.set(0,0,-2.35);station.add(chair);const addChair=(g,m,p,n)=>{const x=new THREE.Mesh(g,m);x.position.set(...p);x.name=n;x.castShadow=x.receiveShadow=true;chair.add(x);return x};addChair(new THREE.CylinderGeometry(.7,.8,.14,16),M.metal,[0,.07,0],'Base');addChair(new THREE.CylinderGeometry(.14,.18,1.1,10),M.metal,[0,.65,0],'Pedestal');addChair(new THREE.BoxGeometry(1.45,.3,1.1),M.leather,[0,1.2,0],'Seat');addChair(new THREE.BoxGeometry(1.3,1.35,.42),M.leather,[0,2.0,-.25],'Backrest');addChair(new THREE.BoxGeometry(.16,.48,.95),M.wood,[-.78,1.45,0],'Armrest');addChair(new THREE.BoxGeometry(.16,.48,.95),M.wood,[.78,1.45,0],'Armrest');addChair(new THREE.BoxGeometry(.85,.3,.35),M.leather,[0,2.85,-.35],'Headrest');addChair(new THREE.BoxGeometry(1.1,.1,.38),M.metal,[0,.72,.7],'Footrest');
for(const x of [-.8,0,.8]){const l=stationMesh(new THREE.CylinderGeometry(.08,.08,.28,8),M.gold,[x,2.65,-4.72],'MirrorLight');l.rotation.x=Math.PI/2}
// door and wall decoration
box([1.25,2.65,.14],M.wood,[3.35,1.42,-5.05],'entrance door');box([.92,1.8,.04],M.glass,[3.35,1.55,-5.14],'door glass');prop(new THREE.TorusGeometry(.08,.025,6,12),M.gold,[2.92,1.5,-5.22],'door handle').rotation.x=Math.PI/2;box([1.2,.7,.08],M.trim,[-2.85,2.35,-5.15],'wall art');
const hemi=new THREE.HemisphereLight(0xb9d8d0,0x17242a,1.8);scene.add(hemi);const key=new THREE.DirectionalLight(0xffd7ad,2.5);key.position.set(-4,7,4);key.castShadow=true;key.shadow.mapSize.set(512,512);scene.add(key);for(const p of [[-1.1,3.7,-4.1],[0,3.7,-4.1],[1.1,3.7,-4.1]]){const l=new THREE.PointLight(0xffbd70,1.5,4);l.position.set(...p);scene.add(l)}
const player=createPlayer(camera,scene,renderer),menu=document.querySelector('.menu'),back=document.querySelector('#shop-back'),controls=document.querySelector('#controls');function enterShop(){menu.classList.add('hidden');back.classList.add('visible');controls.classList.add('visible');controls.setAttribute('aria-hidden','false');document.body.classList.add('in-shop');player.reset()}function exitShop(){menu.classList.remove('hidden');back.classList.remove('visible');controls.classList.remove('visible');controls.setAttribute('aria-hidden','true');document.body.classList.remove('in-shop')}document.querySelector('[data-panel="play"]').addEventListener('click',enterShop);back.addEventListener('click',exitShop);
const modal=document.querySelector('#modal'),content=document.querySelector('#panel-content');const copy={settings:['Settings','Audio, graphics, and controls will be available here.'],about:['About Barber','A stylized first-person barber simulator built for small screens and big style.']};function openPanel(k){content.innerHTML=`<h2>${copy[k][0]}</h2><p>${copy[k][1]}</p>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}function closePanel(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}document.querySelectorAll('[data-panel]:not([data-panel="play"])').forEach(b=>b.addEventListener('click',()=>openPanel(b.dataset.panel)));document.querySelector('.close').addEventListener('click',closePanel);modal.addEventListener('click',e=>{if(e.target===modal)closePanel()});
const clock=new THREE.Clock();function render(){player.update(Math.min(clock.getDelta(),.05));renderer.render(scene,camera);requestAnimationFrame(render)}addEventListener('resize',()=>fitViewport(camera,renderer),{passive:true});fitViewport(camera,renderer);render();
